### ISSUE TITLE
[Request] Provide way to suppress FSI messages

### ISSUE THREAD

**Issue by jmhickman** [fsprojects/FsHttp#100]
Howdy, I'm using FsHttp in my library. As I've used my library in `dotnet fsi`, I've noticed that FsHttp is printing its own messages into the console. 

I'm still pretty new to FSharp, but I looked around in the code and there doesn't seem to be a way to suppress these messages. My library has its own encapsulation of errors and events, so these extra console messages are kind of a distraction. 

I would be appreciative if there were a way to suppress them added. Thank you. If there is a way to do it, I apologize but I couldn't find it.

**Comment by RonaldSchlenker** [comment]
I removed the messages, though I agree that they might be distracting and unnecessary. I release v9.0.6 in a minute. Have a try, and thanks for your suggestion.
