### ISSUE TITLE
Am I using `Config.timeoutInSeconds` wrong?

### ISSUE THREAD

**Issue by jmhickman** [fsprojects/FsHttp#113]
```
GlobalConfig.defaults
|> Config.timeoutInSeconds 28.5
|> GlobalConfig.set
```

When I set this like above, I'm only receiving approximately a 10 second timeout. Is there some maximum value, or is there something I'm doing wrong in globally setting the value?

The reason the timeout is so long is because I'm interacting with a program that will wait on user input, and it might actually take this long for the user to do what they need to do, and thus have the program send me a response to my request.

**Comment by jmhickman** [comment]
I'm able to get the desired behavior when I include a `config_timeoutInSeconds 28.5` inside the computation, so the underlying mechanism seems to be working. But I figured it would be cleaner to use the global setting since the timeout isn't dynamic in any way.

**Comment by RonaldSchlenker** [comment]
This is also related to #37 (see comments).
