### ISSUE TITLE
Remove: printfn "Download response received - starting download..."

### ISSUE THREAD

**Issue by drhumlen** [fsprojects/FsHttp#115]
Hi!

I notice a lot of printing to the console when using some of the methods (`Response.toBytesAsync`). Can we remove that to reduce clutter, or is it possible that some users of the library rely on it?

**Comment by RonaldSchlenker** [comment]
Yes, the console logs should be removed, maybe providing a way of opt-in messages when they are useful in FSI. In upcoming v10, it could be declared as breaking chance, but I have the feeling that it’s not part of the API or behavior contract, and thus no one should rely on it.

**Comment by RonaldSchlenker** [comment]
In10.0.0-preview3, that should be fixed. If you want @drhumlen , you could check it out.
