### ISSUE TITLE
Turning off debug logs in FSI

### ISSUE THREAD

**Issue by naartjie** [fsprojects/FsHttp#121]
Is there a way to turn off the debug logging in FSI?

This is my attempt which only works the 2nd time around. My guess is FsHttp's `doInit` only runs when the `http { ... }` is first called and [overwrites](https://github.com/fsprojects/FsHttp/blob/d377a1f3c3eb239dc69eab72cfa438af34e0bc04/src/FsHttp/FsiInit.fs#L46) my `false` to the default `true` again?

```
FsHttp.Helper.Fsi.logDebugMessages <- false

let! response =
    http {
        POST url
        body
        ContentType "text/xml"
        text reqBody
    }
    |> Request.sendAsync
```

**Comment by RonaldSchlenker** [comment]
Hi, thanks for reporting this issue. I fixed it in `11.0.0` (and also changed the signature / namespace).

It will work like this:

```fsharp
do FsHttp.Fsi.disableDebugLogs()
```

There's a `11.0.0-preview01` available.

**Comment by naartjie** [comment]
Thank you @RonaldSchlenker that's amazing

**Comment by RonaldSchlenker** [comment]
Thank you, too! I'll try to remember this issue the next time trying to explain why mutation in a global context can easily lead to unintended behaviour :)
