### ISSUE TITLE
Async config_transformHttpRequestMessage

### ISSUE THREAD

**Issue by queil** [fsprojects/FsHttp#126]
First I'd like to express my admiration for the project. I like it very much.

I was wondering if there is a way to pre-process message in an async fashion (e.g. Task version like `config_transformHttpRequestMessageTAsync`) or this feature doesn't exist for a reason? 

So far I worked it around in a truly ugly manner but that is not a good solution:
```
    type IRequestContext<'a> with

        [<CustomOperation("config_transformHttpRequestMessageTAsync")>]
        member inline this.TransformHttpRequestMessage
            (
                context: IRequestContext<#IConfigure<ConfigTransformer, _>>,
                transformer: HttpRequestMessage -> Task<HttpRequestMessage>
            ) =
            context.Self.Configure(fun s ->
                { s with
                    httpMessageTransformer = fun m -> (transformer m).GetAwaiter().GetResult() })
```

**Comment by RonaldSchlenker** [comment]
Hi @queil , thanks for the issue.

What's the purpose of having an async message transformer? I could think of such an example:

```fsharp
let request = task {
    let! theContent = File.ReadAllTextAsync("c:/temp/content.txt")
    return! http {
        GET "https://www.wikipedia.de"
        config_transformHttpRequestMessage (fun msg ->
            do msg.Content <- new StringContent(theContent)
            msg
        )
    }
}
```

What we can see in the example is: As soon as an async-fetched value is used in request definition (no matter if it's a header, content, transformer, config value, etc.), the whole request definition has to be lifted to async. It does not matter whether the asynchronous call occurs before the request definition (like in this example) or within - the effect is always the same. This is something that I think is not practicable, since the definition of a request is just data.

**Comment by queil** [comment]
@RonaldSchlenker Thanks for your response. I have a use case in which I asynchronously read request's content and store it (also asynchronously) in a data store before sending. Then such a logging function I can apply in multiple requests (think of a declarative HttpClientHandler). Does this make sense?

**Comment by RonaldSchlenker** [comment]
That sounds to me pretty close to the example I posted above, isn’t it?

**Comment by queil** [comment]
The effect is technically the same in the sense, that yes, in both cases the code runs before the request. But this doesn't feel very elegant. I.e. I hoped to use it like a *pipeline* or *middleware* but I understand, as you said, that rewriting the whole internals to async just to support this is not very practical.

**Comment by RonaldSchlenker** [comment]
If you want, you could provide a more complete example of how you think it could look like. Maybe there’s something in your idea which I don’t see.

**Comment by queil** [comment]
@RonaldSchlenker That's fine. I think I can solve it easily with `DelegatingHandler`.
