### ISSUE TITLE
SchlenkR.FsHttp => FsHttp, error after migrating (FS0708)

### ISSUE THREAD

**Issue by CaptnCodr** [fsprojects/FsHttp#90]
I wanted to migrate from SchlenkR.FsHttp to FsHttp and after restoring I get this error message at every operation, see:
![image](https://user-images.githubusercontent.com/4574031/143095050-b24e95a8-0922-4605-bf25-f993dc3d4fae.png)

**Comment by ronaldschlenker** [comment]
Is it possible to post the code here? This usually happens when custom operation names changed. There were a lot of breaking changes. All Config operations are now prefixed with „config_“ for example.

**Comment by CaptnCodr** [comment]
This is here: https://github.com/CaptnCodr/pushbullet-cli/blob/master/HttpService.fs#L72

**Comment by ronaldschlenker** [comment]
Should be:

```fsharp
http {
    DELETE $"..."
    header "Access-Token" "..."
}
```

**Comment by ronaldschlenker** [comment]
There are conventions for naming custom operations for the builder methods here:

https://github.com/fsprojects/FsHttp/issues/48

**Comment by CaptnCodr** [comment]
Thank you, that helped. 🙂

**Comment by ronaldschlenker** [comment]
If there should come up more issued / ideas or any kind of feedback, feel free to post it.

**Comment by CaptnCodr** [comment]
For sure, Ronald. :)
